const language = [
	...LANG_INDEX_ADD,
	...LANG_INDEX_CHG,
	...LANG_INDEX_DEL,
	...LANG_INDEX_RF,
	...LANG_INDEX,
	...LANG_FLIGHT,
	...LANG_CLASS,
	...LANG_IATA,
	...LANG_TIME,
	...LANG_DATE,
	...LANG_CONTACT,
	...LANG_MESSAGE,
	...LANG_STATUS,
	...LANG_SEGMENT,
	...LANG_PNR
];