const language = [
	...LANG_INDEX_GREEN,
	...LANG_INDEX_YELLOW,
	...LANG_INDEX_RED,
	...LANG_INDEX,
	...LANG_FLIGHT,
	...LANG_CLASS,
	...LANG_IATA,
	...LANG_TIME,
	...LANG_DATE,
	...LANG_CONTACT,
	...LANG_MESSAGE,
	...LANG_STATUS,
	...LANG_SEGMENT,
	...LANG_PNR
];